### ISSUE TITLE
I would like to be able to see who posted a meme

### ISSUE THREAD

**Issue by missamynicholson** [missamynicholson/Memeories#28]
As a curious user
So that I can identify my witty friends 
I would like to be able to see who posted a meme

**Comment by atakanyenel** [comment]
you have to add belongs_to association to your meme model. Your database has no connection between a meme and the user that posts it.
[Rails guide for this](http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association)

**Comment by missamynicholson** [comment]
These are just User Stories that we are working our way through - not issues we are stuck on, but thanks anyway @atayenel!
