### ISSUE TITLE
Few issues discovered during heroku testing

### ISSUE THREAD

**Issue by missamynicholson** [missamynicholson/Memeories#39]
1. Make caption fields longer
2. Show photos/memes in single column
3. Home button
4. Cancel meme creation from the add caption page
5. Allow for a comma in captions

**Comment by ollieh-m** [comment]
Can we add making secret code a secret ENV variable? Sending the code you enter in a form is no less safe than sending your password to the controller to then be encrypted. But just having the secret code in our code on GitHub is less safe...

**Comment by missamynicholson** [comment]
yep, I'll make it an ENV 👍
